# 3) print ბრძანება 20-ჯერ გამოიყენეთ და დაბეჭდეთ თქვენთვის სასურველი ინფორმაცია.
print("barbare")
print("tsivilashvili")
print("old 8")
print("skool")
print("kandidi")
print("lile")
print("tsivilashvili")
print("in me free tame")
print("i read a book")
print("i love plaing vith me sister")
print("i love plaing vith me frands")
print("i love skool")
print("i want to meat new frands")
print("i like me new academy")
print("i love me grup lider")
print("she is moste beutifal persen in me lafe")
print("im good at english")
print("im good at gorgian too")
print("thanks for mom and dad for bringin me here in goa")